### ISSUE TITLE
Fastlane Configuration

### ISSUE THREAD

**Issue by jwenz723** [mmcc007/screenshots#16]
README.md says that this plugin can work with fastlane, but since I am new to fastlane it is not exactly clear how I create a lane that will make use of this plugin.

Can someone provide me with an example fastfile lane configuration that will run the `screenshots` plugin and then upload those screenshots to the apple and android app stores?

I would love to contribute this to the README if someone can point me in the right direction.

**Comment by mmcc007** [comment]
Fledge has fastlane scripts that automate delivery of a Flutter app to both stores:
https://github.com/mmcc007/fledge

These fastlane scripts run on the build server (Travis).

You can see an example at:
https://github.com/mmcc007/todo/blob/dev/ios/fastlane/Fastfile
https://github.com/mmcc007/todo/blob/dev/android/fastlane/Fastfile

Fastlane scripts don't currently include a call to run Screenshots.  But, since the screenshots are checked in to the repo, Fastlane will find them and deliver them.

It is better to run Screenshots locally for now and check the images into the repo (or whatever suits your CI/CD). The reason for this is because android emulators do not behave well in the cloud (plus the fastlane scripts for android and ios run in separate processes).

Would love to see any contributions you think relevant In the meantime, feel free to discuss your interests here or in separate issues.

**Comment by mmcc007** [comment]
So, to follow-up on my last comment, the short answer is:
The recommended way to call `Screenshots` is to call it before calling Fastlane. Fastlane will then find the images in the appropriate place. Fastlane can then upload images to the Apple or Google store consoles.

**Comment by jwenz723** [comment]
Ok, that makes sense. And thanks for the links to the fastfile's for fledge. Those are very helpful. I'll try to get some time to make a PR to update the README with some more clarification on this for future users.

**Comment by jwenz723** [comment]
Looks like the documentation has been added with c59262b. Closing.
