### ISSUE TITLE
Codemagic: Screenshots expects no devices to be running at startup

### ISSUE THREAD

**Issue by kentcb** [mmcc007/screenshots#38]
Hi,

I'm trying to use screenshots in conjunction with [Codemagic](http://codemagic.io/) CI. However, I'm getting this error:

```
# Screenshots expects no devices to be running at startup. 
# Please disconnect all devices and shutdown all simulators/emulators.
```

The message does not tell me what simulators/emulators it found to be running, so I'm not sure whether it's Android, iOS, or both.

Do I have any recourse here, considering I have no control over Codemagic's infrastructure? Is there anything I could ask the Codemagic team in order to get past this problem?

**Comment by mmcc007** [comment]
Screenshots runs
```
flutter devices
```
to determine if anything is running. If it find anything running, it displays the message and exits.
If you can run the same command in CodeMagic you can find out what is running.

Let me know if this resolves the issue for you. If this does not resolve the issue, it may be possible to make screenshots behave better when arbitrary 'devices' are running (hopefully should not be necessary).

**Comment by kentcb** [comment]
Thanks for the tip. `flutter devices` gave me:

```
+ flutter devices
1 connected device:

Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
```

I tried adding a hack in to stop all Android emulators:

```
adb devices | grep emulator | cut -f1 | while read line; do adb -s $line emu kill; done
```

Now I can at least start `screenshots`. So yeah, it would be great if `screenshots` could soldier on despite the presence of running emulators/devices.

Now I've moved onto the next problem, which is that it's complaining about the emulator name:

```
configuration error: emulator not installed for device 'Nexus 6P' in screenshots.yaml.

Install the missing emulator or use a supported device with an installed emulator in screenshots.yaml.

  Installed emulators:
    emulator
    
  Installed simulators:
    iPhone 5s
    <snip>

  Currently supported devices:
    android:
      Nexus 6P
      Nexus 5X
    ios:
      iPhone 7 Plus
      iPad Pro (12.9-inch) (2nd generation)
      iPhone X
```
Seems odd that Nexus 6P is listed as a supported device, but not available for emulation...

**Comment by mmcc007** [comment]
Setting up an Nexus 6P emulator in a CI/CD setting requires some steps. Here is an attempt I made in travis (which does not run x86 as CodeMagic seems to):
https://github.com/mmcc007/screenshots/blob/454c9278886ea2ec6ffa27f743694ff0af49772e/.travis.yml#L35-L44

Your attempts should probably be something similar.

Nexus 6P is listed as supported because there is a matching screen in [screens.yaml](https://github.com/mmcc007/screenshots/blob/master/lib/resources/screens.yaml). Not the clearest messaging, but messaging is being improved.

Let me know if this gets you past this stage and on to the next.

**Comment by kentcb** [comment]
Thanks @mmcc007. I've made some progress. My CI script looks like this:

```
brew update && brew upgrade imagemagick
export PATH=$HOME/programs/flutter/bin/cache/dart-sdk/bin:$HOME/programs/flutter/.pub-cache/bin:$PATH
flutter packages pub global activate screenshots
flutter packages pub global activate grinder

grind pre-build

# HACK: stop all existing devices/emulators
adb devices | grep emulator | cut -f1 | while read line; do adb -s $line emu kill; done
brew cask install android-sdk
EMULATOR_API_LEVEL=22
ABI="default;armeabi-v7a"
EMULATOR_NAME="Nexus_6P_API_28"
yes | sdkmanager --licenses
sdkmanager "system-images;android-$EMULATOR_API_LEVEL;$ABI"
sdkmanager --list | head -15
echo no | avdmanager create avd -n $EMULATOR_NAME -k "system-images;android-$EMULATOR_API_LEVEL;$ABI"
echo "hw.lcd.width=1440" >> ~/.android/avd/$EMULATOR_NAME.avd/config.ini
echo "hw.lcd.height=2560" >> ~/.android/avd/$EMULATOR_NAME.avd/config.ini

screenshots
```

However, the execution seems to hang when starting the emulator:

```
+ screenshots
Warning: 'Nexus 6P' does not have a matching emulator.
       : Using 'Nexus_6P_API_28'.
Clearing images in android/fastlane/metadata/android/en-AU/images/phoneScreenshots for 'Nexus 6P'...
Starting emulator 'Nexus 6P' in locale en-AU ...
```

Any idea what might be amiss?

**Comment by mmcc007** [comment]
Since you already have an avd installed, you may not have to install another one (for now).

The easiest thing for now might be to just rename the existing avd to the desired avd using something like:
```
avdmanager move avd --name emulator --rename Nexus_6P
```

**Comment by kentcb** [comment]
Not having much luck. I decided to switch to running this locally on my Mac. Got everything installed, but when I run:

```
# 'adb' must be in the PATH to use Screenshots
```

I added it to my path and can execute `adb` just fine at the terminal, but it still complains about the same thing.

**Comment by kentcb** [comment]
If I execute the command used to check if adb is installed:

```
which adb && echo adb || echo not installed
```

It does indeed output "not installed". If I do `which adb` on its own at the terminal, it outputs nothing. And yet, if I execute just `adb` it works... Hmmm :confused:

**Comment by kentcb** [comment]
Got past that by closing/reopening terminal. Now hitting:

```
PANIC: Cannot find AVD system path. Please define ANDROID_SDK_ROOT
```

btw, I'll ping if I'm stuck for more than a little while. Just want to record all the small issues I run into for future travelers.

**Comment by mmcc007** [comment]
It's always a good idea to get screenshots working locally before running it in the cloud.

Let me know how you get along.

**Comment by kentcb** [comment]
I have things working on iOS now (locally, that is).

The Android problem was...interesting. It seems the `sdkmanager "system-images;android-$EMULATOR_API_LEVEL;$ABI"` command wasn't enough to actually download the images. When I fired up Android Studio it listed the image under AVDs, but said it needed to be downloaded. Once I did that in Android Studio, `screenshots` could at least run. Of course, I'm concerned that running the `sdkmanager` command on the CI server will result in exactly the same issue, but that's a "later on" problem.

Now I've hit another issue with an assertion failing:

```
DriverError: Error in Flutter application: Uncaught extension error while executing waitFor: 'package:flutter_test/src/all_elements.dart': Failed assertion: line 51 pos 12: 'element != null'; is not true.
```
Looking into that next...

**Comment by kentcb** [comment]
OK, it seems the call to `await FlutterDriver.connect()` is not sufficient for the application to be ready for the subsequent `find.byValueKey` call. If I insert an artificial delay (a few seconds seems fine) after calling `connect` and before calling `find.byValueKey` then it works as expected. Again, this is Android-only - iOS was fine without the artificial delay.

**Comment by mmcc007** [comment]
Looks like you're not the only one with this problem:
https://github.com/flutter/flutter/issues/16991#issuecomment-467729361

By the way, if not already, you should probably be using an x86 accelerated emulator locally (especially since Codemagic seems to be supporting x86 emulators).

Depending on what the cloud supports, running android emulators in the cloud can be a dark art. If you can use accelerated x86, which it seems codemagic supports, you could be in luck (no such luck on travis-ci, etc.. hence all the jumping thru hoops with installing older emulators.)

**Comment by kentcb** [comment]
Just an update from me. I have everything running locally just fine on my Mac (iOS and Android screens captured). However, when I try to run in CodeMagic I still have problems. The last few lines of my log are:

```
+ avdmanager create avd -n Nexus_6P_API_28 -k 'system-images;android-28;default;x86_64'
Loading local repository...                                                     
[=========                              ] 25% Loading local repository...       
[=========                              ] 25% Fetch remote repository...        
[=========                              ] 25% Fetch remote repository...        
[=========                              ] 25% Fetch remote repository...        
[=======================================] 100% Fetch remote repository...       
Parsing /usr/local/Caskroom/android-sdk/4333796/system-images/android-28/default/x86_64/package.xmlParsing /usr/local/Caskroom/android-sdk/4333796/tools/package.xmlAuto-selecting single ABI x86_64
Do you wish to create a custom hardware profile? [no] + screenshots
Warning: 'Nexus 6P' does not have a matching emulator.
       : Using 'Nexus_6P_API_28'.
Warning: 'iPhone X' has multiple iOS versions.
       : Using 'iPhone X' with iOS version com.apple.CoreSimulator.SimRuntime.iOS-12-2 (ID: D32AC305-CD0E-4F7F-A481-47E5C2A2A99B).
Warning: 'iPad Pro (12.9-inch) (2nd generation)' has multiple iOS versions.
       : Using 'iPad Pro (12.9-inch) (2nd generation)' with iOS version com.apple.CoreSimulator.SimRuntime.iOS-12-2 (ID: 6621433E-9FDC-4F4C-B72E-F3C5FC9111D7).
Clearing images in ios/fastlane/screenshots/en-AU for 'iPhone X'...
Clearing images in ios/fastlane/screenshots/en-AU for 'iPad Pro (12.9-inch) (2nd generation)'...
Clearing images in android/fastlane/metadata/android/en-AU/images/phoneScreenshots for 'Nexus 6P'...
Starting emulator 'Nexus 6P' in locale en-AU ...
```

Then it just sits there for ~40 minutes until the build times out. I'm not really sure how to move forward with this.

**Comment by mmcc007** [comment]
Since you're not really installing a 'Nexus 6P' (requires setting up hardware profile)... you are using a generic emulator. Apparently CodeMagic already installs a generic emulator (called 'emulator'). So, to move forward, it might be easier to just rename 'emulator' to 'Nexus_6P'. 

If emulator still does not start you can always try creating a simple integration test and run it on the cloud (using 'flutter drive')... or contact CodeMagic support.

BTW: it's not always desirable to run screenshots in the cloud. Screenshots is generally intended to create images locally, which can then be uploaded to respective stores (I created the cloud version mainly for demo purposes).

**Comment by kentcb** [comment]
Forgot to mention I already tried renaming "emulator" to "Nexus_6P" and it failed with an error saying there is no emulator called "emulator" :confused:

**Comment by mmcc007** [comment]
Disclaimer, I have not used codemagic:

As a sanity test, run a test on codemagic to make sure you can access and run the pre-installed emulator.

Then, on codemagic, to confirm the name of the preinstalled emulator you can run 
```
emulator -list-avds
or
flutter emulators
```
I expect this should return one emulator (called 'emulator')

The following command should then work:
```
avdmanager move avd --name emulator --rename Nexus_6P
```
and screenshots will find it and start it.

**Comment by kentcb** [comment]
Thanks, but tried that already. My script:
```
emulator -list-avds
avdmanager move avd --name emulator --rename Nexus_6P
```

The output:
```
+ emulator -list-avds
emulator
+ avdmanager move avd --name emulator --rename Nexus_6P
Parsing /usr/local/Caskroom/android-sdk/4333796/tools/package.xmlError: There is no valid Android Virtual Device named 'emulator'.
null
```

I'll see if anyone from Codemagic can help.

**Comment by mmcc007** [comment]
Running screenshots in the cloud requires more setup of the android emulators than running locally. In particular, you have to copy the hardware profile (like for Nexus 6P, Nexus 5X, etc... which are usually generated from Android Studio). Without a correctly set-up emulator, you will not get correct screenshots.

The proper fix, and since you may be talking to Codemagic,  is to ask Codemagic if they can support some representative subset of android emulators with hardware profiles (the equivalent of what already comes with iOS simulators).

That is exactly what screenshots anticipates (and is kinda standard on most dev machines). It should then be possible to start and stop these emulators.

If Codemagic will not support emulators with appropriate hardware profiles, you would have to set them up yourself.
BTW:
```
avdmanager list device -c
```
might help here as a starting point.

BTW2:
The error message
```
Parsing /usr/local/Caskroom/android-sdk/4333796/tools/package.xmlError: There is no valid Android Virtual Device named 'emulator'.
```
is a strange one. It might be related to a recent change to Oracle's Java distribution where they removed support for XML from Java 9 and Java 12 (the also completely dropped Java 10 and 11). A fix for this was to revert to Java 8. See
https://stackoverflow.com/questions/55745614/which-jdk-version-do-i-need-for-android-development-command-line-tool

**Comment by mmcc007** [comment]
Looks like this issue is no longer being pursued. Since it is not specifically a screenshots issue I am closing for now. Let me know if you need further assistance with configuring emulators on CodeMagic.

**Comment by kentcb** [comment]
Yeah, I've put this on hold until I have time later. For now I'll just generate screenshots locally. If that becomes a problem I'll pursue getting this running in CI again.

**Comment by kentcb** [comment]
Just wanted to mention I just had the problem again where `adb` would run from terminal but `which adb` would report nothing. Turns out this is a known issue with `which` described [here](https://stackoverflow.com/a/37580022). So I changed my `PATH` to not use `~` to refer to `adb` location and then it worked.
