### ISSUE TITLE
No tablet configuration for Android?

### ISSUE THREAD

**Issue by kentcb** [mmcc007/screenshots#43]
I've just tried adding different devices to my `screenshots.yaml` and quickly found that I can't add arbitrary emulator names, but instead they have to be present in `screens.yaml` (makes sense, in retrospect). The thing is, `screens.yaml` has a very limited range of Android screen sizes (only two, both of which are phones). I would like to include tablet size screenshots in my app store submission (e.g. Nexus 10) but that doesn't seem supported yet? Should it be? I may well be missing something here.

**Comment by mmcc007** [comment]
Devices generally have common screen sizes, so supported devices are listed by screen size in screens.yaml. Originally screenshots was created with a minimum set of supported screen sizes required by the app stores. The intention was that more screen sizes would be added as desired. 

Currently two android and three ios screen sizes are supported. Devices that match an existing screen size can be added, as identified, to the list of devices under existing screen sizes. New screen sizes can be added for devices that do not have an existing matching screen size.

As mentioned in https://github.com/mmcc007/screenshots/issues/8 the main blocker to adding new screen sizes is the availability of art work. If artwork (correctly sized PNGs for status bars, navigation bar and frame... if available) is available, the code will likely work unchanged. 

If you can locate artwork for your desired device that would be great otherwise we have to find a way to create the artwork. Any suggestions?

**Comment by mmcc007** [comment]
I added support for a screen for a default android table (aspect ratio 4:3) in https://github.com/mmcc007/screenshots/commit/4ed9fe7659bece0399078bef490b98afb7e99c17 that supports Nexus 9 (a tablet)
Let me know how that works out for you.

**Comment by mmcc007** [comment]
BTW: Images for Nexus 9 should look something like:
![Nexus 9-1](https://user-images.githubusercontent.com/1980785/58357687-9ed80d00-7e30-11e9-9f04-100d2ae45359.png)

**Comment by kentcb** [comment]
Feeling dumb here as I can't find what branch that commit is part of.

**Comment by kentcb** [comment]
It worked great - thanks!
