### ISSUE TITLE
iOS: Google Maps views are not captured

### ISSUE THREAD

**Issue by sperochon** [mmcc007/screenshots#93]
Hello Maurice,

First, thank you for all your work in your Flutter packages!

I’m a dev too and using your screenshots package saved my day… my week rather ;-)  (Had to generate 300 screenshots / per platform…)

Everything works fine, except in this case:

My app use google maps view
https://pub.dev/packages/google_maps_flutter

and the map is not being captured in the screenshot = it’s empty
It happens only on iOS.

Made with screenshots package
![iPhone 8 Plus-screenshot_5_maps](https://user-images.githubusercontent.com/1877340/62933326-3d399600-bdc2-11e9-8252-bce7bd468c0b.png)

Made manually
![Simulator Screen Shot - iPhone Xs Max - 2019-08-13 at 11 51 51](https://user-images.githubusercontent.com/1877340/62933363-50e4fc80-bdc2-11e9-9692-2f027126ca31.png)

Thanks!

**Comment by mmcc007** [comment]
Glad you were able to make such good use of _screenshots_. 600 screenshots, that's impressive!

_screenshots_ calls
https://github.com/mmcc007/screenshots/blob/61a1af3503548d5b97395fa0d312c8ea7dd66ffa/lib/src/capture_screen.dart#L12
which, in flutter drive, calls
https://github.com/flutter/flutter/blob/aa83b284a45497330577ec51b12472b0c92104a6/packages/flutter_driver/lib/src/driver/driver.dart#L849
which, via the observatory and the flutter engine
https://github.com/flutter/engine/blob/7711efbf062a77f28deac68716f808fba071803a/runtime/service_protocol.cc#L23
ends up talking to the dart VM to get the current screen image.

Based on the flutter engine architecture:
https://github.com/flutter/flutter/wiki/The-Engine-architecture
my guess is that the Google Maps plugin interacts/behaves differently before rendering on iOS and Android and consequently screen capture behaves differently.

It might be worth experimenting with inserting a delay before the screenshot call to allow more time for the screen image to render on iOS.

Since the Google Maps plugin is still in developer preview, and if this issue cannot be resolved, it might be worth opening an issue for the plugin.

Let's see how it goes.

**Comment by tek08** [comment]
Am having same issue over here.  Google Maps has since merged in [[google_maps_flutter] Take snapshot of map #2607](https://github.com/flutter/plugins/pull/2607) to the maps plugin.  That said, it doesn't link up to FlutterDriver's screenshot method.  Been considering workarounds, including some clever image stitching.  Any chance there's a less complicated way?

Edit:

My somewhat gross workaround:
```dart
ProcessResult result = await Process.run('xcrun', [
  'simctl',
  'io',
  'booted',
  'screenshot',
  '/tmp/screenshots/test/screenshot_maps.png'
]);
```

inside the test instead of `await screenshot(...)` if there's a google maps obj on screen.
